[[pages]]
path = "app/home.py",
name = "Home",
icon = "ğŸ“„"

[[pages]]
path = "./app/marker.py",
name = "Marker query",
icon = "ğŸ”"

[[pages]]
path = "./app/explore.py",
name = "Explore data",
icon = "ğŸ“Š"

[[pages]]
path = "./app/eQTL.py",
name = "eQTLs query",
icon = "ğŸ§¬"

[[pages]]
path = "./app/auto.py",
name = "Auto annotation",
icon = "ğŸ¤–"

[[pages]]
path = "./app/batch.py",
name = "Batch correct",
icon = "âš™ï¸"

[[pages]]
path = "./app/scGWAS.py",
name = "Traits enrichment",
icon = "ğŸ“ˆ"
